name: Tests

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
    test:
        name: Test Suite
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v5
            
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: '1.25'
            
            - name: Download Dependencies
              run: go mod download
            
            - name: Run Tests
              run: go test -v ./... -v -race -coverprofile=coverage.out
            
            - name: Upload Coverage Report
              uses: codecov/codecov-action@v5
              with:
                files: coverage.out
                flags: unittests
                name: codecov-umbrella
            
